version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      build:
        context: ../submodules/lnd/docker/btcd/
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        ports:
          - 8334:8334
          - 18334:18334
          - 18556:18556
          - 28902:28902
        entrypoint: ["./start-btcd.sh"]

    btcctl:
        extends: btc
        container_name: btcctl
        links:
            - "btcd:rpcserver"
        entrypoint: ["./start-btcctl.sh"]

    lnd:
        image: lnd
        container_name: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
          - RPC_LISTEN="0.0.0.0:10011"
        ports:
          - 9735:9735
          - 10009:10009
        volumes:
          - shared:/rpc
          - lnd_dir:/root/.lnd
        links:
          - "btcd:blockchain"
        entrypoint: ["./start-lnd.sh"]

    sqk:
        image: sqk
        container_name: sqk
        build:
          context: ../
          dockerfile: docker/sqk/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
          - HEADLESS
        volumes:
          - shared:/rpc
          - lnd_dir:/root/.lnd
        links:
          - "btcd:blockchain"
          - "lnd:lnd"
        entrypoint: ["./start-sqk.sh"]

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # lnd_dir volume is needed for sharing tht tls certificate
  lnd_dir:
    driver: local
