version: '2'
services:

    lnd:
        image: lnd
        container_name: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
          - RPC_LISTEN="0.0.0.0:10009"
        volumes:
          - shared:/rpc
          - lnd_dir:/root/.lnd
        entrypoint: ["./start-lnd.sh"]

    sqk:
        image: sqk
        container_name: sqk
        build:
          context: ../
          dockerfile: docker/sqk/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
          - HEADLESS
        volumes:
          - shared:/rpc
          - lnd_dir:/root/.lnd
        links:
          - "lnd:lnd"
        entrypoint: ["./start-sqk.sh"]

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # lnd_dir volume is needed for sharing tht tls certificate
  lnd_dir:
    driver: local
