version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      build:
        context: ../submodules/lnd/docker/btcd/
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        ports:
          - 8334:8334
          - 18334:18334
          - 18556:18556
          - 28902:28902
        entrypoint: ["./start-btcd.sh"]

    btcctl:
        extends: btc
        container_name: btcctl
        links:
            - "btcd:rpcserver"
        entrypoint: ["./start-btcctl.sh"]


    # ltc is an image of litecoin node which used as base image for ltcd and
    # ltcctl. The environment variables default values determined on stage of
    # container start within starting script.
    ltc:
      image: ltcd
      build:
        context: ../submodules/lnd/docker/ltcd/
      volumes:
            - shared:/rpc
            - litecoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    ltcd:
        extends: ltc
        container_name: ltcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-ltcd.sh"]

    ltcctl:
        extends: ltc
        container_name: ltcctl
        links:
            - "ltcd:rpcserver"
        entrypoint: ["./start-ltcctl.sh"]

    lnd:
        image: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
        entrypoint: ["./start-lnd.sh"]

    sqk:
        image: sqk
        build:
          context: ../
          dockerfile: docker/sqk/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
          - HEADLESS
        volumes:
          - shared:/rpc
          - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
          - DISPLAY=${DISPLAY}
        entrypoint: ["./start-sqk.sh"]

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # litecoin volume is needed for maintaining blockchain persistence
  # during ltcd container recreation.
  litecoin:
    driver: local
