version: '3'
services:

  btcd:
    image: btcd
    container_name: btcd
    build:
      context: ../
      dockerfile: docker/btcd/Dockerfile
    volumes:
      - shared_test:/rpc
      - bitcoin_test:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
    environment:
      - DEBUG
      - MINING_ADDRESS
    ports:
      - 8334:8334
      - 18334:18334
      - 18556:18556
      - 28902:28902
    entrypoint: ["./start-btcd.sh"]

  btcctl:
    image: btcd
    container_name: btcctl
    build:
      context: ../
      dockerfile: docker/btcd/Dockerfile
    volumes:
      - shared_test:/rpc
      - bitcoin_test:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
    environment:
      - DEBUG
      - MINING_ADDRESS
    links:
      - "btcd:rpcserver"
    entrypoint: ["./start-btcctl.sh"]

  electrum:
    image: electrum
    container_name: electrum
    build:
      context: ../
      dockerfile: docker/electrum/Dockerfile
    volumes:
      - shared_test:/rpc
      - bitcoin_test:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
    environment:
      - DEBUG
      - MINING_ADDRESS
    links:
      - "btcd:btcd"
    ports:
      - 50002:50002
    entrypoint: ["./start-electrum.sh"]

  lnd_alice:
    image: lnd
    container_name: lnd_alice
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    volumes:
      - shared_test:/rpc
      - lnd_dir_alice:/root/.lnd
    links:
      - "btcd:blockchain"
    entrypoint: ["./start-lnd.sh"]

  lnd_bob:
    image: lnd
    container_name: lnd_bob
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    volumes:
      - shared_test:/rpc
      - lnd_dir_bob:/root/.lnd
    links:
      - "btcd:blockchain"
    entrypoint: ["./start-lnd.sh"]

  lnd_carol:
    image: lnd
    container_name: lnd_carol
    build:
      context: ../
      dockerfile: docker/lnd/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
    volumes:
      - shared_test:/rpc
      - lnd_dir_carol:/root/.lnd
    links:
      - "btcd:blockchain"
    entrypoint: ["./start-lnd.sh"]

  sqk_alice:
    image: sqk
    container_name: sqk_alice
    build:
      context: ../
      dockerfile: docker/sqk/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
      - HEADLESS
    volumes:
      - shared_test:/rpc
      - lnd_dir_alice:/root/.lnd
    links:
      - "btcd:blockchain"
      - "electrum:electrum"
      - "lnd_alice:lnd"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint: ["./start-sqk.sh"]

  sqk_bob:
    image: sqk
    container_name: sqk_bob
    build:
      context: ../
      dockerfile: docker/sqk/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
      - HEADLESS
    volumes:
      - shared_test:/rpc
      - lnd_dir_bob:/root/.lnd
    links:
      - "btcd:blockchain"
      - "electrum:electrum"
      - "lnd_bob:lnd"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint: ["./start-sqk.sh"]

  sqk_carol:
    image: sqk
    container_name: sqk_carol
    build:
      context: ../
      dockerfile: docker/sqk/Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
      - HEADLESS
    volumes:
      - shared_test:/rpc
      - lnd_dir_carol:/root/.lnd
    links:
      - "btcd:blockchain"
      - "electrum:electrum"
      - "lnd_carol:lnd"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint: ["./start-sqk.sh"]

  test:
    image: test
    container_name: test
    build:
      context: ../
      dockerfile: docker/test/Dockerfile
    links:
      - "btcd:blockchain"
      - "sqk_alice:sqk_alice"
      - "sqk_bob:sqk_bob"
      - "sqk_carol:sqk_carol"
    command: tail -f /dev/null

  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 8080:80

volumes:
  # btcctl and lnd containers.
  shared_test:
    driver: local

  # bitcoin_test volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin_test:
    driver: local

  # lnd_dir volume is needed for sharing tht tls certificate
  lnd_dir_alice:
    driver: local
  lnd_dir_bob:
    driver: local
  lnd_dir_carol:
    driver: local
